"use client";

import { useState } from "react";
import CustomInput from "@/app/components/ui/customInput/customInput";
import CustomTextarea from "@/app/components/ui/customTextarea/customTextarea";
import CustomSwitch from "@/app/components/ui/customSwitch/customSwitch";

export default function AddProductPage() {
  const [isOnSale, setIsOnSale] = useState(false);
  const [formData, setFormData] = useState({
    // Basic product info
    name: "",
    slug: "",
    category: "",
    description: "",
    sku: "",
    status: "active",

    // Pricing
    originalPrice: "",
    salePrice: "",
    discountPercent: "",

    // Stock
    stockQuantity: "",
    stockStatus: "in_stock",

    // Quality and rating
    quality: "",
    rating: "0",

    // Images
    thumbnailUrl: "",
    thumbnailAlt: "",
    // productImages will be handled separately for multiple files
  });

  const [productImages, setProductImages] = useState<
    Array<{ url: string; alt: string }>
  >([]);

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;

    // Auto-generate slug from name
    if (name === "name") {
      const slug = value
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/(^-|-$)/g, "");
      setFormData({
        ...formData,
        [name]: value,
        slug: slug,
      });
    } else {
      setFormData({
        ...formData,
        [name]: value,
      });
    }
  };

  const handleTextareaChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value,
    });
  };

  const handleSelectChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value,
    });
  };

  const handleThumbnailChange = (files: FileList | null) => {
    if (files && files[0]) {
      const file = files[0];
      // In a real app, you'd upload this file and get a URL
      const url = URL.createObjectURL(file);
      setFormData({
        ...formData,
        thumbnailUrl: url,
        thumbnailAlt: `${formData.name} thumbnail`,
      });
    }
  };

  const handleProductImagesChange = (files: FileList | null) => {
    if (files) {
      const newImages = Array.from(files).map((file, index) => ({
        url: URL.createObjectURL(file), // In real app, upload and get actual URL
        alt: `${formData.name} view ${index + 1}`,
      }));
      setProductImages(newImages);
    }
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    // Construct the product object matching the products.ts structure
    const productData = {
      id: Date.now(), // In real app, this would be generated by backend
      name: formData.name,
      slug: formData.slug,
      category: formData.category,

      thumbnail: {
        url: formData.thumbnailUrl,
        alt: formData.thumbnailAlt,
      },

      images: productImages,

      rating: parseFloat(formData.rating),

      pricing: {
        original: parseFloat(formData.originalPrice),
        sale: isOnSale ? parseFloat(formData.salePrice) : null,
        discountPercent: isOnSale ? parseFloat(formData.discountPercent) : null,
      },

      stock: {
        quantity: parseInt(formData.stockQuantity),
        status: formData.stockStatus,
      },

      quality: formData.quality,
      description: formData.description,
      sku: formData.sku,
      status: formData.status,
    };

    console.log("Product Data:", productData);
    // Here you would send this data to your API
  };
  return (
    <div className="space-y-6">
      <h1 className="text-3xl font-bold text-gray-900">Add Product</h1>

      <div className="bg-white rounded-lg shadow p-6">
        <p className="text-gray-600 mb-6">This is the add product demo page.</p>

        <form className="space-y-6" onSubmit={handleSubmit}>
          {/* Basic Product Information */}
          <div className="p-4 bg-blue-50 rounded-lg border border-blue-200">
            <h3 className="text-lg font-semibold text-blue-800 mb-4">
              Basic Information
            </h3>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {/* Product Name */}
              <div>
                <CustomInput
                  id="name"
                  name="name"
                  width="w-full"
                  height="h-[50px]"
                  placeholder="Enter product name"
                  label="Product Name"
                  value={formData.name}
                  onChange={handleInputChange}
                  required
                  border="border border-gray-300 rounded-lg"
                  backgroundColor="bg-white"
                  padding="py-3 px-4"
                />
              </div>

              {/* Auto-generated Slug */}
              <div>
                <CustomInput
                  id="slug"
                  name="slug"
                  width="w-full"
                  height="h-[50px]"
                  placeholder="auto-generated-from-name"
                  label="Product Slug (URL)"
                  value={formData.slug}
                  onChange={handleInputChange}
                  border="border border-gray-300 rounded-lg"
                  backgroundColor="bg-gray-100"
                  padding="py-3 px-4"
                  disabled
                />
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4">
              {/* SKU */}
              <div>
                <CustomInput
                  id="sku"
                  name="sku"
                  width="w-full"
                  height="h-[50px]"
                  placeholder="e.g., CHAIR-WD-001"
                  label="SKU (Stock Keeping Unit)"
                  value={formData.sku}
                  onChange={handleInputChange}
                  required
                  border="border border-gray-300 rounded-lg"
                  backgroundColor="bg-white"
                  padding="py-3 px-4"
                />
              </div>

              {/* Category */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Category <span className="text-red-500">*</span>
                </label>
                <select
                  name="category"
                  value={formData.category}
                  onChange={handleSelectChange}
                  required
                  className="w-full border border-gray-300 bg-white h-[50px] px-3 py-2 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                >
                  <option value="">Select category</option>
                  <option value="furniture">Furniture</option>
                  <option value="office">Office</option>
                  <option value="living-room">Living Room</option>
                  <option value="dining">Dining</option>
                  <option value="bedroom">Bedroom</option>
                  <option value="outdoor">Outdoor</option>
                </select>
              </div>
            </div>

            {/* Product Description */}
            <div className="mt-4">
              <CustomTextarea
                id="description"
                name="description"
                label="Product Description"
                placeholder="Enter detailed product description"
                value={formData.description}
                onChange={handleTextareaChange}
                required
                border="border border-gray-300 rounded-lg"
                backgroundColor="bg-white"
                padding="py-3 px-4"
                rows={4}
              />
            </div>
          </div>

          {/* Product Images */}
          <div className="p-4 bg-purple-50 rounded-lg border border-purple-200">
            <h3 className="text-lg font-semibold text-purple-800 mb-4">
              Product Images
            </h3>

            <div className="space-y-4">
              <CustomInput
                label="Product Thumbnail Image"
                id="thumbnailImage"
                name="thumbnailImage"
                type="file"
                accept="image/*"
                onFileChange={handleThumbnailChange}
                border="border border-gray-300 rounded-lg"
                backgroundColor="bg-white"
                padding="py-3 px-4"
                required
              />

              <CustomInput
                label="Product Images (Multiple)"
                id="productImages"
                name="productImages"
                type="file"
                accept="image/*"
                multiple
                onFileChange={handleProductImagesChange}
                border="border border-gray-300 rounded-lg"
                backgroundColor="bg-white"
                padding="py-3 px-4"
              />
            </div>
          </div>

          {/* Pricing Information */}
          <div className="p-4 bg-green-50 rounded-lg border border-green-200">
            <h3 className="text-lg font-semibold text-green-800 mb-4">
              Pricing Information
            </h3>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {/* Original Price */}
              <div>
                <CustomInput
                  id="originalPrice"
                  name="originalPrice"
                  width="w-full"
                  height="h-[50px]"
                  placeholder="0.00"
                  label="Original Price"
                  type="number"
                  step="0.01"
                  min="0"
                  value={formData.originalPrice}
                  onChange={handleInputChange}
                  required
                  border="border border-gray-300 rounded-lg"
                  backgroundColor="bg-white"
                  padding="py-3 px-4"
                />
              </div>

              {/* Rating */}
              <div>
                <CustomInput
                  id="rating"
                  name="rating"
                  width="w-full"
                  height="h-[50px]"
                  placeholder="0.0"
                  label="Product Rating (0-5)"
                  type="number"
                  step="0.1"
                  min="0"
                  max="5"
                  value={formData.rating}
                  onChange={handleInputChange}
                  border="border border-gray-300 rounded-lg"
                  backgroundColor="bg-white"
                  padding="py-3 px-4"
                />
              </div>
            </div>

            {/* Sale Switch */}
            <div className="mt-4 p-3 bg-white rounded-lg border">
              <CustomSwitch
                id="isOnSale"
                name="isOnSale"
                checked={isOnSale}
                onChange={setIsOnSale}
                label="This product is on sale"
                size="md"
                color="green"
              />
            </div>

            {/* Sale Details - Only show when sale is enabled */}
            {isOnSale && (
              <div className="mt-4 p-4 bg-green-100 rounded-lg border border-green-300">
                <h4 className="text-md font-semibold text-green-800 mb-3">
                  Sale Details
                </h4>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <CustomInput
                      id="salePrice"
                      name="salePrice"
                      width="w-full"
                      height="h-[50px]"
                      placeholder="0.00"
                      label="Sale Price"
                      type="number"
                      step="0.01"
                      min="0"
                      value={formData.salePrice}
                      onChange={handleInputChange}
                      required={isOnSale}
                      border="border border-green-300 rounded-lg"
                      backgroundColor="bg-white"
                      padding="py-3 px-4"
                    />
                  </div>

                  <div>
                    <CustomInput
                      id="discountPercent"
                      name="discountPercent"
                      width="w-full"
                      height="h-[50px]"
                      placeholder="0"
                      label="Discount Percentage (%)"
                      type="number"
                      min="0"
                      max="100"
                      value={formData.discountPercent}
                      onChange={handleInputChange}
                      border="border border-green-300 rounded-lg"
                      backgroundColor="bg-white"
                      padding="py-3 px-4"
                    />
                  </div>
                </div>
              </div>
            )}
          </div>

          {/* Stock & Quality Information */}
          <div className="p-4 bg-orange-50 rounded-lg border border-orange-200">
            <h3 className="text-lg font-semibold text-orange-800 mb-4">
              Stock & Quality
            </h3>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              {/* Stock Quantity */}
              <div>
                <CustomInput
                  id="stockQuantity"
                  name="stockQuantity"
                  width="w-full"
                  height="h-[50px]"
                  placeholder="0"
                  label="Stock Quantity"
                  type="number"
                  min="0"
                  value={formData.stockQuantity}
                  onChange={handleInputChange}
                  required
                  border="border border-gray-300 rounded-lg"
                  backgroundColor="bg-white"
                  padding="py-3 px-4"
                />
              </div>

              {/* Stock Status */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Stock Status <span className="text-red-500">*</span>
                </label>
                <select
                  name="stockStatus"
                  value={formData.stockStatus}
                  onChange={handleSelectChange}
                  required
                  className="w-full border border-gray-300 bg-white h-[50px] px-3 py-2 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                >
                  <option value="in_stock">In Stock</option>
                  <option value="low_stock">Low Stock</option>
                  <option value="out_of_stock">Out of Stock</option>
                </select>
              </div>

              {/* Quality */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Quality Level <span className="text-red-500">*</span>
                </label>
                <select
                  name="quality"
                  value={formData.quality}
                  onChange={handleSelectChange}
                  required
                  className="w-full border border-gray-300 bg-white h-[50px] px-3 py-2 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                >
                  <option value="">Select quality</option>
                  <option value="Basic">Basic</option>
                  <option value="Standard">Standard</option>
                  <option value="Premium">Premium</option>
                  <option value="Luxury">Luxury</option>
                </select>
              </div>
            </div>
          </div>

          {/* Product Status */}
          <div className="p-4 bg-gray-50 rounded-lg border border-gray-200">
            <h3 className="text-lg font-semibold text-gray-800 mb-4">
              Product Status
            </h3>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Status <span className="text-red-500">*</span>
              </label>
              <select
                name="status"
                value={formData.status}
                onChange={handleSelectChange}
                required
                className="w-full md:w-1/3 border border-gray-300 bg-white h-[50px] px-3 py-2 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
              >
                <option value="active">Active</option>
                <option value="inactive">Inactive</option>
                <option value="draft">Draft</option>
              </select>
            </div>
          </div>

          <div className="flex gap-4 pt-6">
            <button
              type="submit"
              className="bg-blue-500 text-white px-8 py-3 rounded-lg hover:bg-blue-600 font-medium"
            >
              Add Product
            </button>
            <button
              type="button"
              className="bg-gray-300 text-gray-700 px-8 py-3 rounded-lg hover:bg-gray-400 font-medium"
            >
              Save as Draft
            </button>
            <button
              type="button"
              className="bg-red-100 text-red-700 px-8 py-3 rounded-lg hover:bg-red-200 font-medium"
            >
              Cancel
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
