'use client';

import { useState } from 'react';
import CustomInput from "@/app/components/ui/customInput/customInput";
import CustomTextarea from "@/app/components/ui/customTextarea/customTextarea";

export default function AddTeamPage() {
  const [formData, setFormData] = useState({
    // Basic info
    name: '',
    slug: '',
    role: '',
    position: '',
    
    // Image
    imageUrl: '',
    imageAlt: '',
    
    // Bio (array of strings)
    bioText: '', // We'll split this into array on submit
    
    // Social links
    linkedinUrl: '',
    instagramUrl: '',
    
    // Order and status
    order: '',
    status: 'active'
  });

  const [bioPoints, setBioPoints] = useState<string[]>(['']);

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    
    // Auto-generate slug from name
    if (name === 'name') {
      const slug = value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
      setFormData({
        ...formData,
        [name]: value,
        slug: slug,
        imageAlt: `${value} - ${formData.position || 'Team Member'}`
      });
    } else if (name === 'position') {
      setFormData({
        ...formData,
        [name]: value,
        imageAlt: `${formData.name} - ${value}`
      });
    } else {
      setFormData({
        ...formData,
        [name]: value,
      });
    }
  };

  const handleTextareaChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value,
    });
  };

  const handleSelectChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value,
    });
  };

  const handleImageChange = (files: FileList | null) => {
    if (files && files[0]) {
      const file = files[0];
      // In a real app, you'd upload this file and get a URL
      const url = URL.createObjectURL(file);
      setFormData({
        ...formData,
        imageUrl: url,
        imageAlt: `${formData.name} - ${formData.position}`
      });
    }
  };

  const addBioPoint = () => {
    setBioPoints([...bioPoints, '']);
  };

  const removeBioPoint = (index: number) => {
    if (bioPoints.length > 1) {
      setBioPoints(bioPoints.filter((_, i) => i !== index));
    }
  };

  const updateBioPoint = (index: number, value: string) => {
    const newBioPoints = [...bioPoints];
    newBioPoints[index] = value;
    setBioPoints(newBioPoints);
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    
    // Construct the team member object matching the team.ts structure
    const teamMemberData = {
      id: Date.now(), // In real app, this would be generated by backend
      name: formData.name,
      slug: formData.slug,
      
      role: formData.role,
      position: formData.position,
      
      image: {
        url: formData.imageUrl,
        alt: formData.imageAlt,
      },
      
      bio: bioPoints.filter(point => point.trim() !== ''), // Remove empty bio points
      
      socialLinks: {
        linkedin: formData.linkedinUrl || null,
        instagram: formData.instagramUrl || null,
      },
      
      order: parseInt(formData.order),
      status: formData.status,
    };
    
    console.log('Team Member Data:', teamMemberData);
    // Here you would send this data to your API
  };

  return (
    <div className="space-y-6">
      <h1 className="text-3xl font-bold text-gray-900">Add Team Member</h1>
      
      <div className="bg-white rounded-lg shadow p-6">
        <p className="text-gray-600 mb-6">Add a new team member to your organization.</p>
        
        <form className="space-y-6" onSubmit={handleSubmit}>
          {/* Basic Information */}
          <div className="p-4 bg-blue-50 rounded-lg border border-blue-200">
            <h3 className="text-lg font-semibold text-blue-800 mb-4">Basic Information</h3>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {/* Full Name */}
              <div>
                <CustomInput
                  id="name"
                  name="name"
                  width="w-full"
                  height="h-[50px]"
                  placeholder="Enter full name"
                  label="Full Name"
                  value={formData.name}
                  onChange={handleInputChange}
                  required
                  border="border border-gray-300 rounded-lg"
                  backgroundColor="bg-white"
                  padding="py-3 px-4"
                />
              </div>

              {/* Auto-generated Slug */}
              <div>
                <CustomInput
                  id="slug"
                  name="slug"
                  width="w-full"
                  height="h-[50px]"
                  placeholder="auto-generated-from-name"
                  label="URL Slug"
                  value={formData.slug}
                  onChange={handleInputChange}
                  border="border border-gray-300 rounded-lg"
                  backgroundColor="bg-gray-100"
                  padding="py-3 px-4"
                  disabled
                />
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4">
              {/* Role */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Role <span className="text-red-500">*</span>
                </label>
                <select 
                  name="role"
                  value={formData.role}
                  onChange={handleSelectChange}
                  required
                  className="w-full border border-gray-300 bg-white h-[50px] px-3 py-2 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                >
                  <option value="">Select role</option>
                  <option value="architecture">Architecture</option>
                  <option value="interior">Interior Design</option>
                  <option value="construction">Construction</option>
                  <option value="project-management">Project Management</option>
                  <option value="sales">Sales</option>
                  <option value="marketing">Marketing</option>
                  <option value="administration">Administration</option>
                </select>
              </div>

              {/* Position */}
              <div>
                <CustomInput
                  id="position"
                  name="position"
                  width="w-full"
                  height="h-[50px]"
                  placeholder="e.g., Lead Architect, Senior Designer"
                  label="Position/Title"
                  value={formData.position}
                  onChange={handleInputChange}
                  required
                  border="border border-gray-300 rounded-lg"
                  backgroundColor="bg-white"
                  padding="py-3 px-4"
                />
              </div>
            </div>
          </div>

          {/* Profile Image */}
          <div className="p-4 bg-purple-50 rounded-lg border border-purple-200">
            <h3 className="text-lg font-semibold text-purple-800 mb-4">Profile Image</h3>
            
            <CustomInput
              label="Profile Photo"
              id="profileImage"
              name="profileImage"
              type="file"
              accept="image/*"
              onFileChange={handleImageChange}
              border="border border-gray-300 rounded-lg"
              backgroundColor="bg-white"
              padding="py-3 px-4"
              required
            />
            
            {formData.imageUrl && (
              <div className="mt-4">
                <p className="text-sm text-gray-600 mb-2">Preview:</p>
                <img 
                  src={formData.imageUrl} 
                  alt={formData.imageAlt}
                  className="w-32 h-32 object-cover rounded-lg border"
                />
              </div>
            )}
          </div>

          {/* Bio Information */}
          <div className="p-4 bg-green-50 rounded-lg border border-green-200">
            <h3 className="text-lg font-semibold text-green-800 mb-4">Bio Information</h3>
            
            <div className="space-y-3">
              {bioPoints.map((bioPoint, index) => (
                <div key={index} className="flex gap-2 items-start">
                  <div className="flex-1">
                    <CustomTextarea
                      id={`bio-${index}`}
                      name={`bio-${index}`}
                      placeholder={`Bio point ${index + 1}...`}
                      value={bioPoint}
                      onChange={(e) => updateBioPoint(index, e.target.value)}
                      border="border border-gray-300 rounded-lg"
                      backgroundColor="bg-white"
                      padding="py-3 px-4"
                      rows={2}
                    />
                  </div>
                  <div className="flex flex-col gap-1 mt-1">
                    <button
                      type="button"
                      onClick={addBioPoint}
                      className="bg-green-500 text-white px-3 py-1 rounded text-sm hover:bg-green-600"
                      title="Add bio point"
                    >
                      +
                    </button>
                    {bioPoints.length > 1 && (
                      <button
                        type="button"
                        onClick={() => removeBioPoint(index)}
                        className="bg-red-500 text-white px-3 py-1 rounded text-sm hover:bg-red-600"
                        title="Remove bio point"
                      >
                        -
                      </button>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Social Links */}
          <div className="p-4 bg-yellow-50 rounded-lg border border-yellow-200">
            <h3 className="text-lg font-semibold text-yellow-800 mb-4">Social Links</h3>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {/* LinkedIn */}
              <div>
                <CustomInput
                  id="linkedinUrl"
                  name="linkedinUrl"
                  width="w-full"
                  height="h-[50px]"
                  placeholder="https://linkedin.com/in/username"
                  label="LinkedIn URL"
                  type="url"
                  value={formData.linkedinUrl}
                  onChange={handleInputChange}
                  border="border border-gray-300 rounded-lg"
                  backgroundColor="bg-white"
                  padding="py-3 px-4"
                />
              </div>

              {/* Instagram */}
              <div>
                <CustomInput
                  id="instagramUrl"
                  name="instagramUrl"
                  width="w-full"
                  height="h-[50px]"
                  placeholder="https://instagram.com/username"
                  label="Instagram URL"
                  type="url"
                  value={formData.instagramUrl}
                  onChange={handleInputChange}
                  border="border border-gray-300 rounded-lg"
                  backgroundColor="bg-white"
                  padding="py-3 px-4"
                />
              </div>
            </div>
          </div>

          {/* Order and Status */}
          <div className="p-4 bg-gray-50 rounded-lg border border-gray-200">
            <h3 className="text-lg font-semibold text-gray-800 mb-4">Display Settings</h3>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {/* Display Order */}
              <div>
                <CustomInput
                  id="order"
                  name="order"
                  width="w-full"
                  height="h-[50px]"
                  placeholder="1"
                  label="Display Order"
                  type="number"
                  min="1"
                  value={formData.order}
                  onChange={handleInputChange}
                  required
                  border="border border-gray-300 rounded-lg"
                  backgroundColor="bg-white"
                  padding="py-3 px-4"
                />
              </div>

              {/* Status */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Status <span className="text-red-500">*</span>
                </label>
                <select 
                  name="status"
                  value={formData.status}
                  onChange={handleSelectChange}
                  required
                  className="w-full border border-gray-300 bg-white h-[50px] px-3 py-2 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                >
                  <option value="active">Active</option>
                  <option value="inactive">Inactive</option>
                </select>
              </div>
            </div>
          </div>

          <div className="flex gap-4 pt-6">
            <button
              type="submit"
              className="bg-blue-500 text-white px-8 py-3 rounded-lg hover:bg-blue-600 font-medium"
            >
              Add Team Member
            </button>
            <button
              type="button"
              className="bg-gray-300 text-gray-700 px-8 py-3 rounded-lg hover:bg-gray-400 font-medium"
            >
              Save as Draft
            </button>
            <button
              type="button"
              className="bg-red-100 text-red-700 px-8 py-3 rounded-lg hover:bg-red-200 font-medium"
            >
              Cancel
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}